###############################################################################
#
# Monitoring-Grafana Project
#
# File:
#   compose.yml
#
# Description:
#   Main Docker Compose entry point.
#
# Repository:
#   https://github.com/gregorku/Monitoring-Grafana
#
# Requirements:
#   Docker Compose v2.20+
#
###############################################################################

name: monitoring-grafana

include:

  ###########################################################################
  # Docker Networks
  ###########################################################################

  - compose/00-networks.yml

  ###########################################################################
  # Reverse Proxy
  ###########################################################################

  - compose/10-traefik.yml

  ###########################################################################
  # Security
  ###########################################################################

  - compose/20-crowdsec.yml

  ###########################################################################
  # Monitoring
  ###########################################################################

  - compose/30-metabase.yml

  ###########################################################################
  # Maintenance
  ###########################################################################

  - compose/40-watchtower.yml

  ###########################################################################
  # Dashboards (public)
  ###########################################################################

  - compose/50-grafana.yml

  ###########################################################################
  # Metrics
  ###########################################################################

  - compose/60-prometheus.yml

  - compose/70-snmp-exporter.yml

  - compose/80-alertmanager.yml

  - compose/81-loki.yml

  - compose/82-alloy.yml

  ###########################################################################
  # Local Overrides
  ###########################################################################

  - compose/99-local.yml
