###############################################################################
#
# Monitoring-Grafana Project
#
# File:
#   compose.yml
#
# Description:
#   Main Docker Compose entry point.
#
# Repository:
#   https://github.com/gregorku/Monitoring-Grafana
#
# Requirements:
#   Docker Compose v2.20+
#
###############################################################################

name: monitoring-grafana

include:

  ###########################################################################
  # Docker Networks
  ###########################################################################

  - compose/00-networks.yml

  ###########################################################################
  # Reverse Proxy
  ###########################################################################

  - compose/10-traefik.yml

  ###########################################################################
  # Metrics
  ###########################################################################

  - compose/20-prometheus.yml

  - compose/30-snmp-exporter.yml

  - compose/40-alertmanager.yml

  - compose/60-loki.yml

  - compose/70-alloy.yml
 
  ###########################################################################
  # Dashboards (public)
  ###########################################################################

  - compose/50-grafana.yml


