###############################################################################
# Alertmanager
###############################################################################
services:

  alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_VERSION}
    container_name: alertmanager
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    ports:

      - "${MONITORING_HOST_IP}:9093:9093"

    volumes:
      - ${DATA_DIR}/alertmanager/data:/alertmanager
      - ../configs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:9093/-/healthy || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:

      monitoring-netcup:
        ipv4_address: ${IP_ALERTMANAGER}

