###############################################################################
# Alertmanager
###############################################################################
services:

  alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_VERSION}
    container_name: alertmanager
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    volumes:
      - ${DATA_DIR}/alertmanager/data:/alertmanager
      - ../configs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:9093/-/healthy || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      bridge-moje:
        ipv4_address: ${IP_ALERTMANAGER}
      traefik-moje:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: "${LOG_MAX_FILES}"
