###############################################################################
# Loki - log storage
###############################################################################
services:

  loki:
    image: grafana/loki:${LOKI_VERSION}
    container_name: loki
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - -config.file=/etc/loki/loki.yml
    ports:

      - "${MONITORING_HOST_IP}:3100:3100"

    volumes:
      - ${DATA_DIR}/loki/data:/loki
      - ../configs/loki/loki.yml:/etc/loki/loki.yml:ro
    networks:

      monitoring-netcup:
        ipv4_address: ${IP_LOKI}

